name: build

on:
  workflow_call:
    inputs:
      mainPipeline:
        description: Distinguish main and PR pipelines
        default: false
        required: false
        type: boolean
      prNumber:
        description: Pull request number
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out the source code
      uses: actions/checkout@v3

    - name: Install
      run: |
        sudo apt install -y \
            bison flex gettext texinfo libncurses5-dev libncursesw5-dev xxd \
            gperf automake libtool pkg-config build-essential gperf genromfs \
            libgmp-dev libmpc-dev libmpfr-dev libisl-dev binutils-dev libelf-dev \
            libexpat-dev gcc-multilib g++-multilib picocom u-boot-tools util-linux
        sudo apt install -y kconfig-frontends
        sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi
        sudo apt install -y git wget flex bison gperf python3 python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
        mkdir -p ~/esp
        git clone --recursive https://github.com/espressif/esp-idf.git -b v5.3 ~/esp/esp-idf
        ~/esp/esp-idf/install.sh esp32

    - name: Run NuttX build
      run: |
        . /home/runner/esp/esp-idf/export.sh
        ./build.sh
